security:
  oauth2:
    client:
      client-id: param
      client-secret: paramjeetsingh
      scope: read,write
      auto-approve-scopes: '.*'
      redirect-uri: http://127.0.0.1:9999/login&response_type=code&state=i1ACMM

facebook:
  client:
    clientId: 317373314949342
    clientSecret: bffa439a2c3c339749ca0782f30ffa5d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
        userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true
