server:
    port : 8080
security:
  oauth2:
    client:
      clientId: 317373314949342
      clientSecret: bffa439a2c3c339749ca0782f30ffa5d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
spring:
  resources:
    chain:
      enabled: true
      